import Head from "next/head";
import { Roboto } from "next/font/google";
import styles from "@/styles/home.module.css";
import Image from "next/image";

import heroImg from "../../public/assets/hero.png";

const roboto = Roboto({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "700", "900"],
});

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${styles.main} ${roboto.className}`}>
                <section className={styles.container}>
                    <div className={styles.logoContent}>
                        <Image
                            className={styles.hero}
                            alt="Logo Tarefas+"
                            src={heroImg}
                            priority
                        />
                    </div>

                    <h1 className={styles.title}>
                        Sistema feito para você organizar <br />
                        seus estudos e tarefas.
                    </h1>

                    <section className={styles.infoContent}>
                        <div className={styles.box}>
                            <span>+12 posts </span>
                        </div>
                        <div className={styles.box}>
                            <span>+90 comentários </span>
                        </div>
                    </section>
                </section>
            </main>
        </>
    );
}
